-- AlterTable
ALTER TABLE "Problem" ALTER COLUMN "rep" SET DEFAULT 1000;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "User" ALTER COLUMN "rep" SET DEFAULT 1000;
